executable = /data/magic/users-ifae/rgrau/EBL-splines/EBL.sh
arguments = -c 6
output = EBL-$(ClusterId).$(ProcId).out
error = EBL-$(ClusterId).$(ProcId).err
log = EBL-$(ClusterId).$(ProcId).log
environment = PATH = $ENV(PATH); SOFT_DIR = /data/magic/users-ifae/rgrau/pythonenv; OTHER_DIR= /data/magic/users-ifae/rgrau/EBL-splines

request_memory = 4 GB
request_cpus = 6
request_disk = 10 GB

notify_user = rgrau@ifae.es
notification = always

queue
